spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/file-upload
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    session:
      store-type: none


  #  h2:
#    console:
#      enabled: true
#      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  batch:
    jdbc:
      initialize-schema: always   # cria as tabelas do batch no H2 automaticamente para demo
    job:
        enable: false



#legacy:
#  datasource:
#    url: jdbc:h2:mem:legacydb;DB_CLOSE_DELAY=-1
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

#logging:
#  level:
#    root: INFO
#    org.springframework.batch: DEBUG
